# Generated by Django 2.2.6 on 2020-01-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('semester', models.PositiveIntegerField()),
                ('branch', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=50)),
                ('notes', models.FileField(upload_to='notes')),
            ],
        ),
    ]
