# Generated by Django 2.2.6 on 2020-01-22 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_notesmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester2Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='Semester_2_Notes')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesModule')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesSemester')),
            ],
        ),
        migrations.CreateModel(
            name='Semester1Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='Semester_1_Notes')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesModule')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesSemester')),
            ],
        ),
    ]
