# Generated by Django 2.2.6 on 2020-01-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0006_semester3subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester1subject',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='semester2subject',
            name='cycle',
        ),
    ]
