# Generated by Django 2.2.6 on 2020-01-26 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0009_semester4subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester4subject',
            name='file',
            field=models.FileField(upload_to='Semester_4_Notes'),
        ),
        migrations.CreateModel(
            name='Semester8Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('teacher', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='Semester_8_Notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesBranch')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesModule')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesSemester')),
            ],
        ),
        migrations.CreateModel(
            name='Semester7Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('teacher', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='Semester_7_Notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesBranch')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesModule')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesSemester')),
            ],
        ),
        migrations.CreateModel(
            name='Semester6Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('teacher', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='Semester_6_Notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesBranch')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesModule')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesSemester')),
            ],
        ),
        migrations.CreateModel(
            name='Semester5Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('teacher', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='Semester_5_Notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesBranch')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesModule')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesSemester')),
            ],
        ),
    ]
