# Generated by Django 2.2.6 on 2021-08-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0010_auto_20200126_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('notes_by', models.CharField(max_length=30)),
                ('module1', models.FileField(upload_to='Notes')),
                ('module2', models.FileField(upload_to='Notes')),
                ('module3', models.FileField(upload_to='Notes')),
                ('module4', models.FileField(upload_to='Notes')),
                ('module5', models.FileField(upload_to='Notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesBranch')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.NotesSemester')),
            ],
        ),
    ]
