# Generated by Django 2.2.6 on 2021-08-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0011_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='module1',
            field=models.FileField(blank=True, upload_to='Notes'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='module2',
            field=models.FileField(blank=True, upload_to='Notes'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='module3',
            field=models.FileField(blank=True, upload_to='Notes'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='module4',
            field=models.FileField(blank=True, upload_to='Notes'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='module5',
            field=models.FileField(blank=True, upload_to='Notes'),
        ),
    ]
