# Generated by Django 2.2.6 on 2021-08-09 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0012_auto_20210809_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module1_rating', models.PositiveIntegerField(blank=True)),
                ('module2_rating', models.PositiveIntegerField(blank=True)),
                ('module3_rating', models.PositiveIntegerField(blank=True)),
                ('module4_rating', models.PositiveIntegerField(blank=True)),
                ('module5_rating', models.PositiveIntegerField(blank=True)),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='semester2subject',
            name='module',
        ),
        migrations.RemoveField(
            model_name='semester2subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='semester3subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='semester3subject',
            name='module',
        ),
        migrations.RemoveField(
            model_name='semester3subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='semester4subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='semester4subject',
            name='module',
        ),
        migrations.RemoveField(
            model_name='semester4subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='semester5subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='semester5subject',
            name='module',
        ),
        migrations.RemoveField(
            model_name='semester5subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='semester6subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='semester6subject',
            name='module',
        ),
        migrations.RemoveField(
            model_name='semester6subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='semester7subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='semester7subject',
            name='module',
        ),
        migrations.RemoveField(
            model_name='semester7subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='semester8subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='semester8subject',
            name='module',
        ),
        migrations.RemoveField(
            model_name='semester8subject',
            name='semester',
        ),
        migrations.DeleteModel(
            name='Semester1Subject',
        ),
        migrations.DeleteModel(
            name='Semester2Subject',
        ),
        migrations.DeleteModel(
            name='Semester3Subject',
        ),
        migrations.DeleteModel(
            name='Semester4Subject',
        ),
        migrations.DeleteModel(
            name='Semester5Subject',
        ),
        migrations.DeleteModel(
            name='Semester6Subject',
        ),
        migrations.DeleteModel(
            name='Semester7Subject',
        ),
        migrations.DeleteModel(
            name='Semester8Subject',
        ),
    ]
