# Generated by Django 2.2.6 on 2020-01-21 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0016_auto_20200120_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 21, 16, 55, 2, 578718)),
        ),
    ]
