# Generated by Django 2.2.6 on 2020-01-22 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0017_auto_20200121_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 22, 11, 30, 53, 942984)),
        ),
    ]
