# Generated by Django 2.2.6 on 2020-01-22 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0019_auto_20200122_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 22, 11, 54, 58, 977820)),
        ),
    ]
