# Generated by Django 2.2.6 on 2020-01-26 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0022_auto_20200126_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 26, 18, 38, 50, 191057)),
        ),
    ]
