# Generated by Django 2.2.6 on 2021-05-07 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0025_auto_20200126_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 7, 18, 12, 0, 831771)),
        ),
    ]
