# Generated by Django 2.2.6 on 2021-08-09 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0026_auto_20210507_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 9, 13, 9, 21, 312773)),
        ),
    ]
