# Generated by Django 2.2.6 on 2021-08-09 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0027_auto_20210809_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 9, 13, 42, 58, 459274)),
        ),
    ]
